### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by nhat416** [antoine1003/resume-terminal#16]
Context

- MacOS Ventura 13.1 M1 chip
- git cloned resume-terminal repo
- went into root folder
- executed "npm install"
- executed "npm build"
- get following error

> \> cv-terminal@2.1.3 build
> \> npx parcel build src/index.html

> 🚨 Build failed.
> 
> Error: Got unexpected null
> 
>   Error: Got unexpected null
>   at nullthrows (/Users/ntran/Documents/projects/resume-terminal/node_modules/nullthrows/nullthrows.js:7:15)
>   at loadConfig (/Users/ntran/Documents/projects/resume-terminal/node_modules/@parcel/core/lib/worker.js:106:51)
>   at async Object.runTransform (/Users/ntran/Documents/projects/resume-terminal/node_modules/@parcel/core/lib/worker.js:125:16)
>   at async Child.handleRequest (/Users/ntran/Documents/projects/resume-terminal/node_modules/@parcel/workers/lib/child.js:217:9)

Please advise

**Comment by antoine1003** [comment]
Hi @nhat416 
Well, I tried the same steps on my windows 10 and I don't have this problem .

What is your npm version ? Mine is 8.1.2 maybe it's related 🤷🏻 code .

I read that deleting the `.parcel-cache` folder in the root project could fix it. You can also try that 😃
