### ISSUE TITLE
|| SPOILER || bug graphique lors d'utilisation d'une commande secrète 

### ISSUE THREAD

**Issue by estebanmathia** [antoine1003/resume-terminal#17]
Bonjour,

Déjà je tiens à dire que l'idée est grave cool du CV, en plus c'est super bien réaliser !
Cependant, lorsque l'on exécute 2fois la commande qui ferai delete le projet, le site devient scrollable horizontalement et verticalement

**Comment by antoine1003** [comment]
Salut,

Merci pour ton message. En effet je viens de tester. Je vais voir si j'ai le temps de regarder ça. N'hésites pas à faire une PR si tu sais le corriger 🗡️ 

A+
