### ISSUE TITLE
Il n'est pas possible d'entrer des commandes depuis Lynx

### ISSUE THREAD

**Issue by Zulgrib** [antoine1003/resume-terminal#2]
La partie terminal du site ne fonctionne pas depuis Lynx Version 2.8.9dev.16, le site ne répond pas.
Seul l'URL «Fork me on Github» réponds aux entrée, et redirige vers ce dépôt git.

**Comment by antoine1003** [comment]
Salut,
Merci pour ton retour, je ne pense pas le rendre accessible pour Lynx. J'ai fais en sorte que ce soit fonctionnel sur les navigateurs par défauts de la browserlist 😄 
A+
