### ISSUE TITLE
Build failed: Could not find module "@parcel/transformer-sass"

### ISSUE THREAD

**Issue by GregLebreton** [antoine1003/resume-terminal#7]
Salut, très beau projet que je voulais reprendre avec des étudiants, malheureusement les dépendances posent problèmes. 
A priori, le package @parcel/transformer-sass n'éxiste plus, ou a été renommé.

**Comment by LaurentRisser** [comment]
Hey @GregLebreton essaye de mettre à jour la lib, j'ai eu le même souci que toi et j'ai résolu le souci avec:
`npm i @parcel/transformer-sass`

**Comment by GregLebreton** [comment]
Oui, merci. J avais omis de faire npm install pour installer les modules... My bad!

**Comment by antoine1003** [comment]
Oui c'est ça il manquait le `npm install`, j'ai rajouté ça dans le README :)
