### ISSUE TITLE
Reflected xss dans l'application

### ISSUE THREAD

**Issue by 0xSeb** [antoine1003/resume-terminal#8]
En entrant un payload sans espace, il est possible de trigger une reflected xss sur ton cv en ligne par exemple:

`<img/src/onerror=alert('xss')>`

**Comment by antoine1003** [comment]
Hello,
Merci pour le retour.
Je ne connais pas trop ce genre d'erreur (sur les images en tout cas), tu sais comment je peux corriger ça? 😄

**Comment by 0xSeb** [comment]
Salut ! Je te conseille de te renseigner sur les XSS sur internet et sur comment "Sanitize user inputs for xss"

Bon courage !

**Comment by antoine1003** [comment]
Je vais regarder ça merci !
